package pe.conadis.tradoc.entity.beans;
// default package
// Generated 12/11/2015 03:26:12 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Acceso generated by hbm2java
 */
@Entity
@Table(name = "ACCESO")
public class Acceso implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private AccesoId id;
	private OpcionMenu opcionMenu;
	private Rol rol;

	public Acceso() {
	}

	public Acceso(AccesoId id, OpcionMenu opcionMenu, Rol rol) {
		this.id = id;
		this.opcionMenu = opcionMenu;
		this.rol = rol;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codRol", column = @Column(name = "COD_ROL", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "codOpcMenu", column = @Column(name = "COD_OPC_MENU", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "codMenu", column = @Column(name = "COD_MENU", nullable = false, precision = 22, scale = 0)) })
	public AccesoId getId() {
		return this.id;
	}

	public void setId(AccesoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "COD_OPC_MENU", referencedColumnName = "COD_OPC_MENU", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "COD_MENU", referencedColumnName = "COD_MENU", nullable = false, insertable = false, updatable = false) })
	public OpcionMenu getOpcionMenu() {
		return this.opcionMenu;
	}

	public void setOpcionMenu(OpcionMenu opcionMenu) {
		this.opcionMenu = opcionMenu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COD_ROL", nullable = false, insertable = false, updatable = false)
	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}


}
