package pe.conadis.tradoc.entity.beans;
// default package
// Generated 12/11/2015 03:26:12 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OpcionMenuId generated by hbm2java
 */
@Embeddable
public class OpcionMenuId implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private Integer codOpcMenu;
	private Integer codMenu;

	public OpcionMenuId() {
	}

	public OpcionMenuId(Integer codOpcMenu, Integer codMenu) {
		this.codOpcMenu = codOpcMenu;
		this.codMenu = codMenu;
	}

	@Column(name = "COD_OPC_MENU", nullable = false, precision = 22, scale = 0)
	public Integer getCodOpcMenu() {
		return this.codOpcMenu;
	}

	public void setCodOpcMenu(Integer codOpcMenu) {
		this.codOpcMenu = codOpcMenu;
	}

	@Column(name = "COD_MENU", nullable = false, precision = 22, scale = 0)
	public Integer getCodMenu() {
		return this.codMenu;
	}

	public void setCodMenu(Integer codMenu) {
		this.codMenu = codMenu;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OpcionMenuId))
			return false;
		OpcionMenuId castOther = (OpcionMenuId) other;

		return ((this.getCodOpcMenu() == castOther.getCodOpcMenu()) || (this
				.getCodOpcMenu() != null && castOther.getCodOpcMenu() != null && this
				.getCodOpcMenu().equals(castOther.getCodOpcMenu())))
				&& ((this.getCodMenu() == castOther.getCodMenu()) || (this
						.getCodMenu() != null && castOther.getCodMenu() != null && this
						.getCodMenu().equals(castOther.getCodMenu())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCodOpcMenu() == null ? 0 : this.getCodOpcMenu()
						.hashCode());
		result = 37 * result
				+ (getCodMenu() == null ? 0 : this.getCodMenu().hashCode());
		return result;
	}

}
