package pe.conadis.tradoc.entity.beans;
// default package
// Generated 12/11/2015 03:26:12 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OpcionMenu generated by hbm2java
 */
@Entity
@Table(name = "OPCION_MENU")
public class OpcionMenu implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private OpcionMenuId id;
	private MenuSistema menuSistema;
	private String desOpcMenu;
	private String indEstado;
	private String url;
	private String urlIcon;
	private Set<Acceso> accesos = new HashSet<Acceso>(0);

	public OpcionMenu() {
	}

	public OpcionMenu(OpcionMenuId id, MenuSistema menuSistema) {
		this.id = id;
		this.menuSistema = menuSistema;
	}

	public OpcionMenu(OpcionMenuId id, MenuSistema menuSistema,
			String desOpcMenu, String indEstado, String url, String urlIcon, Set<Acceso> accesos) {
		this.id = id;
		this.menuSistema = menuSistema;
		this.desOpcMenu = desOpcMenu;
		this.indEstado = indEstado;
		this.url = url;
		this.urlIcon = urlIcon;
		this.accesos = accesos;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codOpcMenu", column = @Column(name = "COD_OPC_MENU", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "codMenu", column = @Column(name = "COD_MENU", nullable = false, precision = 22, scale = 0)) })
	public OpcionMenuId getId() {
		return this.id;
	}

	public void setId(OpcionMenuId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COD_MENU", nullable = false, insertable = false, updatable = false)
	public MenuSistema getMenuSistema() {
		return this.menuSistema;
	}

	public void setMenuSistema(MenuSistema menuSistema) {
		this.menuSistema = menuSistema;
	}

	@Column(name = "DES_OPC_MENU", length = 100)
	public String getDesOpcMenu() {
		return this.desOpcMenu;
	}

	public void setDesOpcMenu(String desOpcMenu) {
		this.desOpcMenu = desOpcMenu;
	}

	@Column(name = "IND_ESTADO", length = 1)
	public String getIndEstado() {
		return this.indEstado;
	}

	public void setIndEstado(String indEstado) {
		this.indEstado = indEstado;
	}

	@Column(name = "URL", length = 100)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "URL_ICON", length = 100)
	public String getUrlIcon() {
		return urlIcon;
	}

	public void setUrlIcon(String urlIcon) {
		this.urlIcon = urlIcon;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "opcionMenu")
	public Set<Acceso> getAccesos() {
		return this.accesos;
	}

	public void setAccesos(Set<Acceso> accesos) {
		this.accesos = accesos;
	}

}
