package pe.conadis.tradoc.entity.beans;
// default package
// Generated 12/11/2015 12:56:38 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RolUsuario generated by hbm2java
 */
@Entity
@Table(name = "ROL_USUARIO")
public class RolUsuario implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private RolUsuarioId id;
	private Usuario usuario;
	private Rol rol;

	public RolUsuario() {
	}

	public RolUsuario(RolUsuarioId id) {
		this.id = id;
	}

	public RolUsuario(RolUsuarioId id, Usuario usuario, Rol rol) {
		this.id = id;
		this.usuario = usuario;
		this.rol = rol;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codRol", column = @Column(name = "COD_ROL", precision = 22, scale = 0)),
			@AttributeOverride(name = "idUsuario", column = @Column(name = "ID_USUARIO", precision = 22, scale = 0)) })
	public RolUsuarioId getId() {
		return this.id;
	}

	public void setId(RolUsuarioId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_USUARIO", insertable = false, updatable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COD_ROL", insertable = false, updatable = false)
	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

}
