package pe.conadis.tradoc.entity.beans;

// default package
// Generated 12/11/2015 12:56:38 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.NamedQuery;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "USUARIO")
@NamedQuery(name = "Usuario.findAll", query = "SELECT u FROM Usuario u")
public class Usuario implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private Integer idUsuario;
	private String codUsuario;
	private String password;
	private String indEstado;
	private String indJefeMp;
	private String indJefeUoNivel1;
	private String indJefeUoNivel2;
	private String desCorreo;
	private Date fecCreacion;
	private String codUsuCreacion;
	private Date fecModificacion;
	private String codUsuModificacion;
	private Set<RolUsuario> rolUsuarios = new HashSet<RolUsuario>(0);
	private Personal personal;
	private UnidadOrganica unidadOrganica;

	public Usuario() {
	}

	public Usuario(Integer idUsuario, String codUsuario, String password) {
		this.idUsuario = idUsuario;
		this.codUsuario = codUsuario;
		this.password = password;
	}

	public Usuario(Integer idUsuario, String codUsuario, String password,
			BigDecimal codUo, BigDecimal codPersona, String indEstado,
			String indJefeMp, String indJefeUoNivel1, String indJefeUoNivel2,
			String desCorreo, Date fecCreacion, String codUsuCreacion,
			Date fecModificacion, String codUsuModificacion,
			Set<RolUsuario> rolUsuarios) {
		this.idUsuario = idUsuario;
		this.codUsuario = codUsuario;
		this.password = password;
		this.indEstado = indEstado;
		this.indJefeMp = indJefeMp;
		this.indJefeUoNivel1 = indJefeUoNivel1;
		this.indJefeUoNivel2 = indJefeUoNivel2;
		this.desCorreo = desCorreo;
		this.fecCreacion = fecCreacion;
		this.codUsuCreacion = codUsuCreacion;
		this.fecModificacion = fecModificacion;
		this.codUsuModificacion = codUsuModificacion;
		this.rolUsuarios = rolUsuarios;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "ID_USUARIO")
	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "COD_USUARIO", nullable = false, length = 100)
	public String getCodUsuario() {
		return this.codUsuario;
	}

	public void setCodUsuario(String codUsuario) {
		this.codUsuario = codUsuario;
	}

	@Column(name = "PASSWORD", nullable = false, length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "IND_ESTADO", length = 1)
	public String getIndEstado() {
		return this.indEstado;
	}

	public void setIndEstado(String indEstado) {
		this.indEstado = indEstado;
	}

	@Column(name = "IND_JEFE_MP", length = 1)
	public String getIndJefeMp() {
		return this.indJefeMp;
	}

	public void setIndJefeMp(String indJefeMp) {
		this.indJefeMp = indJefeMp;
	}

	@Column(name = "IND_JEFE_UO_NIVEL1", length = 1)
	public String getIndJefeUoNivel1() {
		return this.indJefeUoNivel1;
	}

	public void setIndJefeUoNivel1(String indJefeUoNivel1) {
		this.indJefeUoNivel1 = indJefeUoNivel1;
	}

	@Column(name = "IND_JEFE_UO_NIVEL2", length = 1)
	public String getIndJefeUoNivel2() {
		return this.indJefeUoNivel2;
	}

	public void setIndJefeUoNivel2(String indJefeUoNivel2) {
		this.indJefeUoNivel2 = indJefeUoNivel2;
	}

	@Column(name = "DES_CORREO", length = 100)
	public String getDesCorreo() {
		return this.desCorreo;
	}

	public void setDesCorreo(String desCorreo) {
		this.desCorreo = desCorreo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FEC_CREACION", length = 7)
	public Date getFecCreacion() {
		return this.fecCreacion;
	}

	public void setFecCreacion(Date fecCreacion) {
		this.fecCreacion = fecCreacion;
	}

	@Column(name = "COD_USU_CREACION", length = 100)
	public String getCodUsuCreacion() {
		return this.codUsuCreacion;
	}

	public void setCodUsuCreacion(String codUsuCreacion) {
		this.codUsuCreacion = codUsuCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FEC_MODIFICACION", length = 7)
	public Date getFecModificacion() {
		return this.fecModificacion;
	}

	public void setFecModificacion(Date fecModificacion) {
		this.fecModificacion = fecModificacion;
	}

	@Column(name = "COD_USU_MODIFICACION", length = 100)
	public String getCodUsuModificacion() {
		return this.codUsuModificacion;
	}

	public void setCodUsuModificacion(String codUsuModificacion) {
		this.codUsuModificacion = codUsuModificacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<RolUsuario> getRolUsuarios() {
		return this.rolUsuarios;
	}

	public void setRolUsuarios(Set<RolUsuario> rolUsuarios) {
		this.rolUsuarios = rolUsuarios;
	}

	// bi-directional many-to-one association to UnidadOrganica
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "COD_UO")
	public UnidadOrganica getUnidadOrganica() {
		return this.unidadOrganica;
	}

	public void setUnidadOrganica(UnidadOrganica unidadOrganica) {
		this.unidadOrganica = unidadOrganica;
	}

	// bi-directional many-to-one association to Personal
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "COD_PERSONA")
	public Personal getPersonal() {
		return this.personal;
	}

	public void setPersonal(Personal personal) {
		this.personal = personal;
	}

}
