package pe.conadis.tradoc.entity;

// Generated Feb 27, 2014 5:00:05 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Afiche generated by hbm2java
 */
@Entity
@Table(name = "X_AFICHE")
public class Afiche implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8064320278311921507L;
	
	private Integer idafiche;
	private char estado;
	private String direccion;
	private String direccionMiniatura;
	private String descripcion;
	private Date fechacreacion;
	private String tipoafiche;
	private Character todas;
	private Character miniatura;
	private Date fechaactualizacion;
	private String video;
	private Set<AficheOficina> aficheOficinas = new HashSet<AficheOficina>(0);

	public Afiche() {
	}

	public Afiche(Integer idafiche, char estado, String direccion,
			String descripcion) {
		this.idafiche = idafiche;
		this.estado = estado;
		this.direccion = direccion;
		this.descripcion = descripcion;
	}

	public Afiche(Integer idafiche, char estado, String direccion,
			String descripcion, Date fechacreacion, String tipoafiche,
			Character todas, Character miniatura, Date fechaactualizacion, String video,
			Set<AficheOficina> aficheOficinas) {
		this.idafiche = idafiche;
		this.estado = estado;
		this.direccion = direccion;
		this.descripcion = descripcion;
		this.fechacreacion = fechacreacion;
		this.tipoafiche = tipoafiche;
		this.todas = todas;
		this.miniatura = miniatura;
		this.fechaactualizacion = fechaactualizacion;
		this.video = video;
		this.aficheOficinas = aficheOficinas;
	}

	@Id
	@Column(name = "IDAFICHE", unique = true, nullable = false, precision = 22, scale = 0)
	//@SequenceGenerator(name = "seq_obs_person", sequenceName = "SEQ_OBS_PERSON", allocationSize = 1)
   // @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_obs_person")
	@GeneratedValue(strategy=GenerationType.AUTO)
	public Integer getIdafiche() {
		return this.idafiche;
	}

	public void setIdafiche(Integer idafiche) {
		this.idafiche = idafiche;
	}

	@Column(name = "ESTADO", nullable = false, length = 1)
	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

	@Column(name = "DIRECCION", nullable = false, length = 200)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}
	
	@Transient
	public String getDireccionMiniatura(){
		return this.direccionMiniatura;
	}
	
	public void setDireccionMiniatura(String direccionMiniatura){
		this.direccionMiniatura = direccionMiniatura;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHACREACION", length = 7)
	public Date getFechacreacion() {
		return this.fechacreacion;
	}

	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}

	@Column(name = "TIPOAFICHE", length = 1)
	public String getTipoafiche() {
		return this.tipoafiche;
	}

	public void setTipoafiche(String tipoafiche) {
		this.tipoafiche = tipoafiche;
	}

	@Column(name = "TODAS", length = 1)
	public Character getTodas() {
		return this.todas;
	}

	public void setTodas(Character todas) {
		this.todas = todas;
	}

	@Column(name = "MINIATURA", length = 1)
	public Character getMiniatura() {
		return this.miniatura;
	}

	public void setMiniatura(Character miniatura) {
		this.miniatura = miniatura;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHAACTUALIZACION", length = 7)
	public Date getFechaactualizacion() {
		return this.fechaactualizacion;
	}
	
	public void setFechaactualizacion(Date fechaactualizacion) {
		this.fechaactualizacion = fechaactualizacion;
	}
	
	@Column(name = "VIDEO", length = 200)
	public String getVideo() {
		return this.video;
	}
	
	public void setVideo(String video) {
		this.video = video;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "afiche")
	public Set<AficheOficina> getAficheOficinas() {
		return this.aficheOficinas;
	}

	public void setAficheOficinas(Set<AficheOficina> aficheOficinas) {
		this.aficheOficinas = aficheOficinas;
	}
	
	public boolean esAficheVideo(){
		return this.getTipoafiche().equals("v");
	}
	
	public boolean esAficheImagen(){
		return this.getTipoafiche().equals("i");
	}

}
