package pe.conadis.tradoc.entity;

// Generated Feb 27, 2014 5:00:05 PM by Hibernate Tools 4.0.0

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Comunicado generated by hbm2java
 */
@Entity
@Table(name = "X_COMUNICADO")
public class Comunicado implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6590142958919078797L;
	
	private Integer idcomunicado;
	private String titulo;
	private String descripcion;
	private String descripcion2;
	private Character estado;
	private Date fechacreacion;
	private String url;
	private String tipocomunicado;
	private Date fechaactualizacion;
	private List<ComunicadoOficina> comunicadoOficinas = new ArrayList<ComunicadoOficina>(
			0);

	public Comunicado() {
	}

	public Comunicado(Integer idcomunicado) {
		this.idcomunicado = idcomunicado;
	}

	public Comunicado(Integer idcomunicado, String titulo,
			String descripcion, String descripcion2, Character estado, Date fechacreacion,
			String url,String tipocomunicado,Date fechaactualizacion, List<ComunicadoOficina> comunicadoOficinas) {
		this.idcomunicado = idcomunicado;
		this.titulo = titulo;
		this.descripcion = descripcion;
		this.descripcion2 = descripcion2;
		this.estado = estado;
		this.fechacreacion = fechacreacion;
		this.url = url;
		this.tipocomunicado = tipocomunicado;
		this.comunicadoOficinas = comunicadoOficinas;
		this.fechaactualizacion = fechaactualizacion;
	}

	@Id
	@Column(name = "IDCOMUNICADO", unique = true, nullable = false, precision = 22, scale = 0)
	//@SequenceGenerator(name = "seq_comunicado", sequenceName = "SEQ_COMUNICADO", allocationSize = 1)
    //@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_comunicado")
	@GeneratedValue(strategy=GenerationType.AUTO)
	public Integer getIdcomunicado() {
		return this.idcomunicado;
	}

	public void setIdcomunicado(Integer idcomunicado) {
		this.idcomunicado = idcomunicado;
	}

	@Column(name = "TITULO", length = 120)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}
	
	@Lob
	@Column(name = "DESC2")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
	
	@Column(name = "DESCRIPCION", length = 4000)
	public String getDescripcion2() {
		return this.descripcion2;
	}

	public void setDescripcion2(String descripcion2) {
		this.descripcion2 = descripcion2;
	}

	@Column(name = "ESTADO", length = 1)
	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHACREACION", length = 7)
	public Date getFechacreacion() {
		return this.fechacreacion;
	}

	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}

	@Column(name = "URL", length = 200)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}
	
	@Column(name = "TIPOCOMUNICADO", length = 50)
	public String getTipocomunicado() {
		return this.tipocomunicado;
	}

	public void setTipocomunicado(String tipocomunicado) {
		this.tipocomunicado = tipocomunicado;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHAACTUALIZACION", length = 7)
	public Date getFechaactualizacion() {
		return this.fechaactualizacion;
	}

	public void setFechaactualizacion(Date fechaactualizacion) {
		this.fechaactualizacion = fechaactualizacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "comunicado")
	public List<ComunicadoOficina> getComunicadoOficinas() {
		return this.comunicadoOficinas;
	}

	public void setComunicadoOficinas(List<ComunicadoOficina> comunicadoOficinas) {
		this.comunicadoOficinas = comunicadoOficinas;
	}

	public boolean esComunicadoImagen(){
		return tipocomunicado.trim().equals("Imagen");
	}
}
