package pe.conadis.tradoc.entity;

// Generated Feb 27, 2014 5:00:05 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ComunicadoOficinaId generated by hbm2java
 */
@Embeddable
public class ComunicadoOficinaId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7750687285426933931L;
	
	private Integer idcomunicado;
	private Integer idoficina;

	public ComunicadoOficinaId() {
	}

	public ComunicadoOficinaId(Integer idcomunicado, Integer idoficina) {
		this.idcomunicado = idcomunicado;
		this.idoficina = idoficina;
	}

	@Column(name = "IDCOMUNICADO", precision = 22, scale = 0)
	public Integer getIdcomunicado() {
		return this.idcomunicado;
	}

	public void setIdcomunicado(Integer idcomunicado) {
		this.idcomunicado = idcomunicado;
	}

	@Column(name = "IDOFICINA", precision = 22, scale = 0)
	public Integer getIdoficina() {
		return this.idoficina;
	}

	public void setIdoficina(Integer idoficina) {
		this.idoficina = idoficina;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ComunicadoOficinaId))
			return false;
		ComunicadoOficinaId castOther = (ComunicadoOficinaId) other;

		return ((this.getIdcomunicado() == castOther.getIdcomunicado()) || (this
				.getIdcomunicado() != null
				&& castOther.getIdcomunicado() != null && this
				.getIdcomunicado().equals(castOther.getIdcomunicado())))
				&& ((this.getIdoficina() == castOther.getIdoficina()) || (this
						.getIdoficina() != null
						&& castOther.getIdoficina() != null && this
						.getIdoficina().equals(castOther.getIdoficina())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getIdcomunicado() == null ? 0 : this.getIdcomunicado()
						.hashCode());
		result = 37 * result
				+ (getIdoficina() == null ? 0 : this.getIdoficina().hashCode());
		return result;
	}

}
