package pe.conadis.tradoc.entity;

// Generated Feb 27, 2014 5:00:05 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ComunicadoOficina generated by hbm2java
 */
@Entity
@Table(name = "X_COMUNICADO_OFICINA")
public class ComunicadoOficina implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2166482365158180955L;
	
	private ComunicadoOficinaId id;
	private Oficina oficina;
	private Comunicado comunicado;

	public ComunicadoOficina() {
	}

	public ComunicadoOficina(ComunicadoOficinaId id) {
		this.id = id;
	}

	public ComunicadoOficina(ComunicadoOficinaId id, Oficina oficina,
			Comunicado comunicado) {
		this.id = id;
		this.oficina = oficina;
		this.comunicado = comunicado;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idcomunicado", column = @Column(name = "IDCOMUNICADO", precision = 22, scale = 0)),
			@AttributeOverride(name = "idoficina", column = @Column(name = "IDOFICINA", precision = 22, scale = 0)) })
	public ComunicadoOficinaId getId() {
		return this.id;
	}

	public void setId(ComunicadoOficinaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDOFICINA", insertable = false, updatable = false)
	public Oficina getOficina() {
		return this.oficina;
	}

	public void setOficina(Oficina oficina) {
		this.oficina = oficina;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDCOMUNICADO", insertable = false, updatable = false)
	public Comunicado getComunicado() {
		return this.comunicado;
	}

	public void setComunicado(Comunicado comunicado) {
		this.comunicado = comunicado;
	}

}
