package pe.conadis.tradoc.entity;

// Generated Feb 27, 2014 5:00:05 PM by Hibernate Tools 4.0.0

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contrato generated by hbm2java
 */
@Entity
@Table(name = "X_CONTRATO")
public class Contrato implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2876061969721161420L;
	
	private Integer idcontrato;
	private String gastos;
	private Date fechacreacion;
	private Character estado;
	private List<NotariaContrato> notariaContratos = new ArrayList<NotariaContrato>(
			0);
	private String descripcion;
	
	public Contrato(Integer idcontrato) {
		this.idcontrato = idcontrato;
	}
	
	public Contrato(String descripcion, String gastos) {
		this.descripcion = descripcion;
		this.gastos = gastos;
	}

	public Contrato(Integer idcontrato, String gastos, Date fechacreacion,
			Character estado, String descripcion, List<NotariaContrato> notariaContratos) {
		this.idcontrato = idcontrato;
		this.gastos = gastos;
		this.fechacreacion = fechacreacion;
		this.estado = estado;
		this.descripcion = descripcion;
		this.notariaContratos = notariaContratos;
	}

	@Id
	@Column(name = "IDCONTRATO", unique = true, nullable = false, precision = 22, scale = 0)
	//@SequenceGenerator(name = "seq_contrato", sequenceName = "SEQ_CONTRATO", allocationSize = 1)
    //@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_contrato")
	@GeneratedValue(strategy=GenerationType.AUTO)
	public Integer getIdcontrato() {
		return this.idcontrato;
	}

	public void setIdcontrato(Integer idcontrato) {
		this.idcontrato = idcontrato;
	}

	@Column(name = "GASTOS", length = 150)
	public String getGastos() {
		return this.gastos;
	}

	public void setGastos(String gastos) {
		this.gastos = gastos;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHACREACION", length = 7)
	public Date getFechacreacion() {
		return this.fechacreacion;
	}

	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}

	@Column(name = "ESTADO", length = 1)
	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contrato")
	public List<NotariaContrato> getNotariaContratos() {
		return this.notariaContratos;
	}

	public void setNotariaContratos(List<NotariaContrato> notariaContratos) {
		this.notariaContratos = notariaContratos;
	}
	
	@Column(name = "DESCRIPCION", length = 200)
	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Contrato() {
	}

}
