package pe.conadis.tradoc.entity;
// default package
// Generated 20/11/2015 12:26:11 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Courier generated by hbm2java
 */
@Entity
@Table(name = "COURIER")
public class Courier implements java.io.Serializable {

	private Integer codCourier;
	private String desCourier;
	private Character insEstado;
	private Set<IncidenciaMensajeria> incidenciaMensajerias = new HashSet<IncidenciaMensajeria>(0);

	public Courier() {
	}

	public Courier(Integer codCourier) {
		this.codCourier = codCourier;
	}

	public Courier(Integer codCourier, String desCourier,
			Character insEstado, Set<IncidenciaMensajeria> incidenciaMensajerias) {
		this.codCourier = codCourier;
		this.desCourier = desCourier;
		this.insEstado = insEstado;
		this.incidenciaMensajerias = incidenciaMensajerias;
	}

	@Id
	@Column(name = "COD_COURIER", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getCodCourier() {
		return this.codCourier;
	}

	public void setCodCourier(Integer codCourier) {
		this.codCourier = codCourier;
	}

	@Column(name = "DES_COURIER", length = 100)
	public String getDesCourier() {
		return this.desCourier;
	}

	public void setDesCourier(String desCourier) {
		this.desCourier = desCourier;
	}

	@Column(name = "INS_ESTADO", length = 1)
	public Character getInsEstado() {
		return this.insEstado;
	}

	public void setInsEstado(Character insEstado) {
		this.insEstado = insEstado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "courier")
	public Set<IncidenciaMensajeria> getIncidenciaMensajerias() {
		return this.incidenciaMensajerias;
	}

	public void setIncidenciaMensajerias(Set<IncidenciaMensajeria> incidenciaMensajerias) {
		this.incidenciaMensajerias = incidenciaMensajerias;
	}

}
