package pe.conadis.tradoc.entity;
// default package
// Generated 20/11/2015 12:26:11 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import pe.conadis.tradoc.entity.beans.Documento;

/**
 * IncidenciaMensajeria generated by hbm2java
 */
@Entity
@Table(name = "INCIDENCIA_MENSAJERIA")
public class IncidenciaMensajeria implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8244016426984281813L;
	private Integer codIncMensajeria;
	private Documento documento;
	private Courier courier;
	private String desNomMensajro;
	private Character indEstMensajeria;
	private String desObservacion;
	private Date fecCreacion;
	private String codUsuCreacion;
	private Date fecModificacion;
	private String codUsuModificacion;
	
	private String fecCreacionFormato;//Transient

	public IncidenciaMensajeria() {
	}

	public IncidenciaMensajeria(Integer codIncMensajeria) {
		this.codIncMensajeria = codIncMensajeria;
	}

	public IncidenciaMensajeria(Integer codIncMensajeria,
			Documento documento, Courier courier, String desNomMensajro,
			Character indEstMensajeria, String desObservacion,
			Date fecCreacion, String codUsuCreacion, Date fecModificacion,
			String codUsuModificacion) {
		this.codIncMensajeria = codIncMensajeria;
		this.documento = documento;
		this.courier = courier;
		this.desNomMensajro = desNomMensajro;
		this.indEstMensajeria = indEstMensajeria;
		this.desObservacion = desObservacion;
		this.fecCreacion = fecCreacion;
		this.codUsuCreacion = codUsuCreacion;
		this.fecModificacion = fecModificacion;
		this.codUsuModificacion = codUsuModificacion;
	}

	@Id
	@Column(name = "COD_INC_MENSAJERIA", unique = true, nullable = false, precision = 22, scale = 0)
	@SequenceGenerator(name = "seq_incid", sequenceName = "SEQ_INCIDENCIA_MENSAJERIA", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_incid")
	public Integer getCodIncMensajeria() {
		return this.codIncMensajeria;
	}

	public void setCodIncMensajeria(Integer codIncMensajeria) {
		this.codIncMensajeria = codIncMensajeria;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "COD_DOCUMENTO")
	public Documento getDocumento() {
		return this.documento;
	}

	public void setDocumento(Documento documento) {
		this.documento = documento;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "COD_COURIER")
	public Courier getCourier() {
		return this.courier;
	}

	public void setCourier(Courier courier) {
		this.courier = courier;
	}

	@Column(name = "DES_NOM_MENSAJRO", length = 100)
	public String getDesNomMensajro() {
		return this.desNomMensajro;
	}

	public void setDesNomMensajro(String desNomMensajro) {
		this.desNomMensajro = desNomMensajro;
	}

	@Column(name = "IND_EST_MENSAJERIA", length = 1)
	public Character getIndEstMensajeria() {
		return this.indEstMensajeria;
	}

	public void setIndEstMensajeria(Character indEstMensajeria) {
		this.indEstMensajeria = indEstMensajeria;
	}

	@Column(name = "DES_OBSERVACION", length = 500)
	public String getDesObservacion() {
		return this.desObservacion;
	}

	public void setDesObservacion(String desObservacion) {
		this.desObservacion = desObservacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FEC_CREACION", length = 7)
	public Date getFecCreacion() {
		return this.fecCreacion;
	}

	public void setFecCreacion(Date fecCreacion) {
		this.fecCreacion = fecCreacion;
	}

	@Column(name = "COD_USU_CREACION", length = 100)
	public String getCodUsuCreacion() {
		return this.codUsuCreacion;
	}

	public void setCodUsuCreacion(String codUsuCreacion) {
		this.codUsuCreacion = codUsuCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FEC_MODIFICACION", length = 7)
	public Date getFecModificacion() {
		return this.fecModificacion;
	}

	public void setFecModificacion(Date fecModificacion) {
		this.fecModificacion = fecModificacion;
	}

	@Column(name = "COD_USU_MODIFICACION", length = 100)
	public String getCodUsuModificacion() {
		return this.codUsuModificacion;
	}

	public void setCodUsuModificacion(String codUsuModificacion) {
		this.codUsuModificacion = codUsuModificacion;
	}

	@Transient
	public String getFecCreacionFormato() {
		return fecCreacionFormato;
	}

	public void setFecCreacionFormato(String fecCreacionFormato) {
		this.fecCreacionFormato = fecCreacionFormato;
	}
	
	

}
