package pe.conadis.tradoc.entity;

// Generated Feb 27, 2014 5:00:05 PM by Hibernate Tools 4.0.0

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Notaria generated by hbm2java
 */
@Entity
@Table(name = "X_NOTARIA")
public class Notaria implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6296618737211989151L;
	
	private Integer idnotaria;
	private Plaza plaza;
	private String paginaweb;
	private String direccion;
	private String telefono1;
	private String telefono2;
	private String nombre;
	private Date fechacreacion;
	private Date fechaactualizacion;
	private Character estado;
	private List<NotariaContrato> notariaContratos = new ArrayList<NotariaContrato>(
			0);
	
	private String email;

	public Notaria() {
	}

	public Notaria(Integer idnotaria, String paginaweb) {
		this.idnotaria = idnotaria;
		this.paginaweb = paginaweb;
	}

	public Notaria(Integer idnotaria, Plaza plaza, String paginaweb,
			String direccion, String telefono1, String telefono2,
			String nombre, Date fechacreacion, Character estado,
			List<NotariaContrato> notariaContratos) {
		this.idnotaria = idnotaria;
		this.plaza = plaza;
		this.paginaweb = paginaweb;
		this.direccion = direccion;
		this.telefono1 = telefono1;
		this.telefono2 = telefono2;
		this.nombre = nombre;
		this.fechacreacion = fechacreacion;
		this.estado = estado;
		this.notariaContratos = notariaContratos;
	}

	@Id
	@Column(name = "IDNOTARIA", unique = true, nullable = false, precision = 22, scale = 0)
	//@SequenceGenerator(name = "seq_notaria", sequenceName = "SEQ_NOTARIA", allocationSize = 1)
    //@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_notaria")
	@GeneratedValue(strategy=GenerationType.AUTO)
	public Integer getIdnotaria() {
		return this.idnotaria;
	}

	public void setIdnotaria(Integer idnotaria) {
		this.idnotaria = idnotaria;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "IDPLAZA", nullable= true)
	public Plaza getPlaza() {
		return this.plaza;
	}

	public void setPlaza(Plaza plaza) {
		this.plaza = plaza;
	}

	@Column(name = "PAGINAWEB", length = 600)
	public String getPaginaweb() {
		return this.paginaweb;
	}

	public void setPaginaweb(String paginaweb) {
		this.paginaweb = paginaweb;
	}

	@Column(name = "DIRECCION", length = 200)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "TELEFONO1", length = 50)
	public String getTelefono1() {
		return this.telefono1;
	}

	public void setTelefono1(String telefono1) {
		this.telefono1 = telefono1;
	}

	@Column(name = "TELEFONO2", length = 10)
	public String getTelefono2() {
		return this.telefono2;
	}

	public void setTelefono2(String telefono2) {
		this.telefono2 = telefono2;
	}

	@Column(name = "NOMBRE", length = 60)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHACREACION", length = 7)
	public Date getFechacreacion() {
		return this.fechacreacion;
	}

	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}

	@Column(name = "ESTADO", length = 1)
	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}
	
	
	@Column(name = "EMAIL", length = 150)
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "notaria")
	public List<NotariaContrato> getNotariaContratos() {
		return this.notariaContratos;
	}

	public void setNotariaContratos(List<NotariaContrato> notariaContratos) {
		this.notariaContratos = notariaContratos;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHAACTUALIZACION", length = 7)
	public Date getFechaactualizacion() {
		return fechaactualizacion;
	}

	public void setFechaactualizacion(Date fechaactualizacion) {
		this.fechaactualizacion = fechaactualizacion;
	}
	
	

}
