package pe.conadis.tradoc.entity;

// Generated Feb 27, 2014 5:00:05 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NotariaContratoId generated by hbm2java
 */
@Embeddable
public class NotariaContratoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5043602687395770479L;
	
	private Integer idnotaria;
	private Integer idcontrato;

	public NotariaContratoId() {
	}

	public NotariaContratoId(Integer idnotaria, Integer idcontrato) {
		this.idnotaria = idnotaria;
		this.idcontrato = idcontrato;
	}

	@Column(name = "IDNOTARIA", precision = 22, scale = 0)
	public Integer getIdnotaria() {
		return this.idnotaria;
	}

	public void setIdnotaria(Integer idnotaria) {
		this.idnotaria = idnotaria;
	}

	@Column(name = "IDCONTRATO", precision = 22, scale = 0)
	public Integer getIdcontrato() {
		return this.idcontrato;
	}

	public void setIdcontrato(Integer idcontrato) {
		this.idcontrato = idcontrato;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NotariaContratoId))
			return false;
		NotariaContratoId castOther = (NotariaContratoId) other;

		return ((this.getIdnotaria() == castOther.getIdnotaria()) || (this
				.getIdnotaria() != null && castOther.getIdnotaria() != null && this
				.getIdnotaria().equals(castOther.getIdnotaria())))
				&& ((this.getIdcontrato() == castOther.getIdcontrato()) || (this
						.getIdcontrato() != null
						&& castOther.getIdcontrato() != null && this
						.getIdcontrato().equals(castOther.getIdcontrato())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdnotaria() == null ? 0 : this.getIdnotaria().hashCode());
		result = 37
				* result
				+ (getIdcontrato() == null ? 0 : this.getIdcontrato()
						.hashCode());
		return result;
	}

}
