package pe.conadis.tradoc.entity;

// Generated Feb 27, 2014 5:00:05 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Nota generated by hbm2java
 */
@Entity
@Table(name = "X_NOTA")
public class Nota implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1754617612187287305L;
	
	private Integer idnota;
	private String titulo;
	private String descripcion;
	private Date fechacreacion;
	private Character estado;
	private Set<Subcapitulo> subcapitulos = new HashSet<Subcapitulo>(0);
	private Set<Capitulo> capitulosForIdnotainicial = new HashSet<Capitulo>(0);
	private Set<Capitulo> capitulosForIdnotafinal = new HashSet<Capitulo>(0);
	private Set<Rubro> rubros = new HashSet<Rubro>(0);

	public Nota() {
	}

	public Nota(Integer idnota) {
		this.idnota = idnota;
	}

	public Nota(Integer idnota, String titulo, String descripcion,
			Date fechacreacion, Character estado,
			Set<Subcapitulo> subcapitulos,
			Set<Capitulo> capitulosForIdnotainicial,
			Set<Capitulo> capitulosForIdnotafinal, Set<Rubro> rubros) {
		this.idnota = idnota;
		this.titulo = titulo;
		this.descripcion = descripcion;
		this.fechacreacion = fechacreacion;
		this.estado = estado;
		this.subcapitulos = subcapitulos;
		this.capitulosForIdnotainicial = capitulosForIdnotainicial;
		this.capitulosForIdnotafinal = capitulosForIdnotafinal;
		this.rubros = rubros;
	}

	@Id
	@Column(name = "IDNOTA", unique = true, nullable = false, precision = 22, scale = 0)
	//@SequenceGenerator(name = "seq_nota", sequenceName = "SEQ_NOTA", allocationSize = 1)
    //@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_nota")
	@GeneratedValue(strategy=GenerationType.AUTO)
	public Integer getIdnota() {
		return this.idnota;
	}

	public void setIdnota(Integer idnota) {
		this.idnota = idnota;
	}

	@Column(name = "TITULO", length = 200)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	//@Lob
	@Column(name = "DESCRIPCION", length = 4000)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHACREACION", length = 7)
	public Date getFechacreacion() {
		return this.fechacreacion;
	}

	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}

	@Column(name = "ESTADO", length = 1)
	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nota")
	public Set<Subcapitulo> getSubcapitulos() {
		return this.subcapitulos;
	}

	public void setSubcapitulos(Set<Subcapitulo> subcapitulos) {
		this.subcapitulos = subcapitulos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "notaByIdnotainicial")
	public Set<Capitulo> getCapitulosForIdnotainicial() {
		return this.capitulosForIdnotainicial;
	}

	public void setCapitulosForIdnotainicial(
			Set<Capitulo> capitulosForIdnotainicial) {
		this.capitulosForIdnotainicial = capitulosForIdnotainicial;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "notaByIdnotafinal")
	public Set<Capitulo> getCapitulosForIdnotafinal() {
		return this.capitulosForIdnotafinal;
	}

	public void setCapitulosForIdnotafinal(Set<Capitulo> capitulosForIdnotafinal) {
		this.capitulosForIdnotafinal = capitulosForIdnotafinal;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nota")
	public Set<Rubro> getRubros() {
		return this.rubros;
	}

	public void setRubros(Set<Rubro> rubros) {
		this.rubros = rubros;
	}

}
