package pe.conadis.tradoc.entity;

// Generated Feb 27, 2014 5:00:05 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OcurrenciaMuro generated by hbm2java
 */
@Entity
@Table(name = "X_OCURRENCIA_MURTEC")
public class OcurrenciaMuro implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3927705255689896141L;
	
	private Integer idocurrencia;
	private Oficina oficina;
	private String opcion;
	private Date fecha;

	public OcurrenciaMuro() {
	}

	public OcurrenciaMuro(Integer idocurrencia) {
		this.idocurrencia = idocurrencia;
	}

	public OcurrenciaMuro(Integer idocurrencia, Oficina oficina,
			String opcion, Date fecha) {
		this.idocurrencia = idocurrencia;
		this.oficina = oficina;
		this.opcion = opcion;
		this.fecha = fecha;
	}

	@Id
	@Column(name = "IDOCURRENCIA", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getIdocurrencia() {
		return this.idocurrencia;
	}

	public void setIdocurrencia(Integer idocurrencia) {
		this.idocurrencia = idocurrencia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDOFICINA")
	public Oficina getOficina() {
		return this.oficina;
	}

	public void setOficina(Oficina oficina) {
		this.oficina = oficina;
	}

	@Column(name = "OPCION", length = 20)
	public String getOpcion() {
		return this.opcion;
	}

	public void setOpcion(String opcion) {
		this.opcion = opcion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA", length = 7)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
