package pe.conadis.tradoc.entity;

// Generated Feb 27, 2014 5:00:05 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PerfilPrivilegioId generated by hbm2java
 */
@Embeddable
public class PerfilPrivilegioId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2854648019134160072L;
	
	private Integer idperfil;
	private Integer idprivilegio;

	public PerfilPrivilegioId() {
	}

	public PerfilPrivilegioId(Integer idperfil, Integer idprivilegio) {
		this.idperfil = idperfil;
		this.idprivilegio = idprivilegio;
	}

	@Column(name = "IDPERFIL", precision = 22, scale = 0)
	public Integer getIdperfil() {
		return this.idperfil;
	}

	public void setIdperfil(Integer idperfil) {
		this.idperfil = idperfil;
	}

	@Column(name = "IDPRIVILEGIO", precision = 22, scale = 0)
	public Integer getIdprivilegio() {
		return this.idprivilegio;
	}

	public void setIdprivilegio(Integer idprivilegio) {
		this.idprivilegio = idprivilegio;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PerfilPrivilegioId))
			return false;
		PerfilPrivilegioId castOther = (PerfilPrivilegioId) other;

		return ((this.getIdperfil() == castOther.getIdperfil()) || (this
				.getIdperfil() != null && castOther.getIdperfil() != null && this
				.getIdperfil().equals(castOther.getIdperfil())))
				&& ((this.getIdprivilegio() == castOther.getIdprivilegio()) || (this
						.getIdprivilegio() != null
						&& castOther.getIdprivilegio() != null && this
						.getIdprivilegio().equals(castOther.getIdprivilegio())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdperfil() == null ? 0 : this.getIdperfil().hashCode());
		result = 37
				* result
				+ (getIdprivilegio() == null ? 0 : this.getIdprivilegio()
						.hashCode());
		return result;
	}

}
