package pe.conadis.tradoc.entity;

// Generated Feb 27, 2014 5:00:05 PM by Hibernate Tools 4.0.0

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Perfil generated by hbm2java
 */
@Entity
@Table(name = "X_PERFIL")
public class Perfil implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2643268039520170847L;
	
	private Integer idperfil;
	private String descripcion;
	private Character estado;
	private Date fechacreacion;
	private String codigo;
	private List<PerfilPrivilegio> perfilPrivilegios = new ArrayList<PerfilPrivilegio>(
			0);
	private List<xUsuario> usuarios = new ArrayList<xUsuario>(0);

	public Perfil() {
	}

	public Perfil(Integer idperfil) {
		this.idperfil = idperfil;
	}

	public Perfil(Integer idperfil, String descripcion, Character estado,
			Date fechacreacion, String codigo,
			List<PerfilPrivilegio> perfilPrivilegios, List<xUsuario> usuarios) {
		this.idperfil = idperfil;
		this.descripcion = descripcion;
		this.estado = estado;
		this.fechacreacion = fechacreacion;
		this.codigo = codigo;
		this.perfilPrivilegios = perfilPrivilegios;
		this.usuarios = usuarios;
	}

	@Id
	@Column(name = "IDPERFIL", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getIdperfil() {
		return this.idperfil;
	}

	public void setIdperfil(Integer idperfil) {
		this.idperfil = idperfil;
	}

	@Column(name = "DESCRIPCION", length = 120)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ESTADO", length = 1)
	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHACREACION", length = 7)
	public Date getFechacreacion() {
		return this.fechacreacion;
	}

	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}

	@Column(name = "CODIGO", length = 20)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
	public List<PerfilPrivilegio> getPerfilPrivilegios() {
		return this.perfilPrivilegios;
	}

	public void setPerfilPrivilegios(List<PerfilPrivilegio> perfilPrivilegios) {
		this.perfilPrivilegios = perfilPrivilegios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
	public List<xUsuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(List<xUsuario> usuarios) {
		this.usuarios = usuarios;
	}

}
