package pe.conadis.tradoc.entity;

// Generated Feb 27, 2014 5:00:05 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PerfilPrivilegio generated by hbm2java
 */
@Entity
@Table(name = "X_PERFIL_PRIVILEGIO")
public class PerfilPrivilegio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4267741867436744670L;
	
	private PerfilPrivilegioId id;
	private Privilegio privilegio;
	private Perfil perfil;

	public PerfilPrivilegio() {
	}

	public PerfilPrivilegio(PerfilPrivilegioId id) {
		this.id = id;
	}

	public PerfilPrivilegio(PerfilPrivilegioId id, Privilegio privilegio,
			Perfil perfil) {
		this.id = id;
		this.privilegio = privilegio;
		this.perfil = perfil;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idperfil", column = @Column(name = "IDPERFIL", precision = 22, scale = 0)),
			@AttributeOverride(name = "idprivilegio", column = @Column(name = "IDPRIVILEGIO", precision = 22, scale = 0)) })
	public PerfilPrivilegioId getId() {
		return this.id;
	}

	public void setId(PerfilPrivilegioId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDPRIVILEGIO", insertable = false, updatable = false)
	public Privilegio getPrivilegio() {
		return this.privilegio;
	}

	public void setPrivilegio(Privilegio privilegio) {
		this.privilegio = privilegio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDPERFIL", insertable = false, updatable = false)
	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

}
