package pe.conadis.tradoc.entity;

// Generated Feb 27, 2014 5:00:05 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Plaza generated by hbm2java
 */
@Entity
@Table(name = "X_PLAZA")
public class Plaza implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7405420435510837826L;
	
	private Integer idplaza;
	private String nombre;
	private String descripcion;
	private Character estado;
	private Date fechacreacion;
	private String zona;
	private Set<Oficina> oficinas = new HashSet<Oficina>(0);
	private Set<Notaria> notarias = new HashSet<Notaria>(0);

	public Plaza() {
	}

	public Plaza(String nombre) {
		this.nombre = nombre;
	}

	public Plaza(Integer idplaza) {
		this.idplaza = idplaza;
	}

	public Plaza(Integer idplaza, String nombre, String descripcion,
			Character estado, Date fechacreacion, String zona, Set<Oficina> oficinas,
			Set<Notaria> notarias) {
		this.idplaza = idplaza;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.estado = estado;
		this.fechacreacion = fechacreacion;
		this.zona = zona;
		this.oficinas = oficinas;
		this.notarias = notarias;
	}

	@Id
	@Column(name = "IDPLAZA", unique = true, nullable = false, precision = 22, scale = 0)
	//@SequenceGenerator(name = "seq_plaza", sequenceName = "SEQ_PLAZA", allocationSize = 1)
    //@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_plaza")
	@GeneratedValue(strategy=GenerationType.AUTO)
	public Integer getIdplaza() {
		return this.idplaza;
	}

	public void setIdplaza(Integer idplaza) {
		this.idplaza = idplaza;
	}

	@Column(name = "NOMBRE", length = 60)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DESCRIPCION", length = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ESTADO", length = 1)
	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHACREACION", length = 7)
	public Date getFechacreacion() {
		return this.fechacreacion;
	}

	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}
	
	@Column(name = "ZONA", length = 200)
	public String getZona() {
		return this.zona;
	}

	public void setZona(String zona) {
		this.zona = zona;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "plaza")
	public Set<Oficina> getOficinas() {
		return this.oficinas;
	}

	public void setOficinas(Set<Oficina> oficinas) {
		this.oficinas = oficinas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "plaza")
	public Set<Notaria> getNotarias() {
		return this.notarias;
	}

	public void setNotarias(Set<Notaria> notarias) {
		this.notarias = notarias;
	}

}
