package pe.conadis.tradoc.entity;

// Generated Feb 27, 2014 5:00:05 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Privilegio generated by hbm2java
 */
@Entity
@Table(name = "X_PRIVILEGIO")
public class Privilegio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6630707719952925039L;
	
	private Integer idprivilegio;
	private String url;
	private String descripcion;
	private Character estado;
	private Date fechacreacion;
	private Integer idpadre;
	private Integer nivel;
	private String icono;
	private Set<PerfilPrivilegio> perfilPrivilegios = new HashSet<PerfilPrivilegio>(
			0);
	private Set<LogMuro> logMuros = new HashSet<LogMuro>(0);

	public Privilegio() {
	}

	public Privilegio(Integer idprivilegio) {
		this.idprivilegio = idprivilegio;
	}

	public Privilegio(Integer idprivilegio, String url, String descripcion,
			Character estado, Date fechacreacion, Integer idpadre,
			Integer nivel, String icono,
			Set<PerfilPrivilegio> perfilPrivilegios, Set<LogMuro> logMuros) {
		this.idprivilegio = idprivilegio;
		this.url = url;
		this.descripcion = descripcion;
		this.estado = estado;
		this.fechacreacion = fechacreacion;
		this.idpadre = idpadre;
		this.nivel = nivel;
		this.icono = icono;
		this.perfilPrivilegios = perfilPrivilegios;
		this.logMuros = logMuros;
	}

	@Id
	@Column(name = "IDPRIVILEGIO", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getIdprivilegio() {
		return this.idprivilegio;
	}

	public void setIdprivilegio(Integer idprivilegio) {
		this.idprivilegio = idprivilegio;
	}

	@Column(name = "URL", length = 200)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "DESCRIPCION", length = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ESTADO", length = 1)
	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHACREACION", length = 7)
	public Date getFechacreacion() {
		return this.fechacreacion;
	}

	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}

	@Column(name = "IDPADRE", precision = 22, scale = 0)
	public Integer getIdpadre() {
		return this.idpadre;
	}

	public void setIdpadre(Integer idpadre) {
		this.idpadre = idpadre;
	}

	@Column(name = "NIVEL", precision = 22, scale = 0)
	public Integer getNivel() {
		return this.nivel;
	}

	public void setNivel(Integer nivel) {
		this.nivel = nivel;
	}

	@Column(name = "ICONO", length = 20)
	public String getIcono() {
		return this.icono;
	}

	public void setIcono(String icono) {
		this.icono = icono;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "privilegio")
	public Set<PerfilPrivilegio> getPerfilPrivilegios() {
		return this.perfilPrivilegios;
	}

	public void setPerfilPrivilegios(Set<PerfilPrivilegio> perfilPrivilegios) {
		this.perfilPrivilegios = perfilPrivilegios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "privilegio")
	public Set<LogMuro> getLogMuros() {
		return this.logMuros;
	}

	public void setLogMuros(Set<LogMuro> logMuros) {
		this.logMuros = logMuros;
	}

}
