package pe.conadis.tradoc.entity;

// Generated Feb 27, 2014 5:00:05 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VariablesGenerales generated by hbm2java
 */
@Entity
@Table(name = "X_VARIABLES_GENERALES")
public class VariablesGenerales implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3148831418651808419L;
	
	private Integer idvariable;
	private String codigo;
	private String valor;
	private String tipo;
	private Date fechacreacion;
	private Character estado;
	private String descripcion;

	public VariablesGenerales() {
	}

	public VariablesGenerales(Integer idvariable) {
		this.idvariable = idvariable;
	}

	public VariablesGenerales(Integer idvariable, String codigo,
			String valor, String tipo, Date fechacreacion, Character estado,
			String descripcion) {
		this.idvariable = idvariable;
		this.codigo = codigo;
		this.valor = valor;
		this.tipo = tipo;
		this.fechacreacion = fechacreacion;
		this.estado = estado;
		this.descripcion = descripcion;
	}

	@Id
	@Column(name = "IDVARIABLE", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getIdvariable() {
		return this.idvariable;
	}

	public void setIdvariable(Integer idvariable) {
		this.idvariable = idvariable;
	}

	@Column(name = "CODIGO", length = 60)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "VALOR", length = 60)
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	@Column(name = "TIPO", length = 1)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHACREACION", length = 7)
	public Date getFechacreacion() {
		return this.fechacreacion;
	}

	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}

	@Column(name = "ESTADO", length = 1)
	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

	@Column(name = "DESCRIPCION", length = 400)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
