package pe.conadis.tradoc.entity;

// Generated Feb 27, 2014 5:00:05 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "X_USUARIO")
public class xUsuario implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3863627623677641042L;
	
	private Integer idusuario;
	private Perfil perfil;
	private String codigo;
	private String nombres;
	private Character estado;
	private Date fechacreacion;
	private Set<LogMuro> logMuros = new HashSet<LogMuro>(0);

	public xUsuario() {
	}

	public xUsuario(Integer idusuario) {
		this.idusuario = idusuario;
	}

	public xUsuario(Integer idusuario, Perfil perfil, String codigo,
			String nombres, Character estado, Date fechacreacion,
			Set<LogMuro> logMuros) {
		this.idusuario = idusuario;
		this.perfil = perfil;
		this.codigo = codigo;
		this.nombres = nombres;
		this.estado = estado;
		this.fechacreacion = fechacreacion;
		this.logMuros = logMuros;
	}

	@Id
	@Column(name = "IDUSUARIO", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(Integer idusuario) {
		this.idusuario = idusuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDPERFIL")
	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

	@Column(name = "CODIGO", length = 20)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "NOMBRES", length = 80)
	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	@Column(name = "ESTADO", length = 1)
	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHACREACION", length = 7)
	public Date getFechacreacion() {
		return this.fechacreacion;
	}

	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<LogMuro> getLogMuros() {
		return this.logMuros;
	}

	public void setLogMuros(Set<LogMuro> logMuros) {
		this.logMuros = logMuros;
	}

}
